services:
  postgres-time:
    image: postgres
    restart: ${RESTART}
    environment:
      POSTGRES_DB: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-time-postgres:/var/lib/postgresql/data

volumes:
  docker-time-postgres: